name: CI Checks (Python formatting & Docker Build)

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  format_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.x'
          
      - name: Install Black
        run: pip install black
        
      - name: Run Black formatting check
        run: black --check .
  
  docker_build_check:
    runs-on: ubuntu-latest
    needs: format_check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create temporary .env for build test
        run: |
          echo "Some=secrets" > .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Compose Config Check
        run: docker compose config

      - name: Docker Compose Build Test
        run: docker compose build --no-cache
